# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    azureSubscription: 'Pay-As-You-Go(b2f1e96a-2500-4557-9658-7dea028c06a4)'
    command: 'restore'
    projects: 'pipelines-dotnet-core.csproj'
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  inputs:
    azureSubscription: 'Pay-As-You-Go(b2f1e96a-2500-4557-9658-7dea028c06a4)'
    command: 'build'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'drop'
    publishLocation: 'pipeline'